all:
	g++ sphere_scene_part1.cpp -o sphere_scene_part1 -I/usr/X11R6/include/ -L/usr/X11R6/lib -lX11 -lglut -LGLU -I/usr/include/eigen3/
	g++ sphere_scene_flat-shading.cpp -o sphere_scene_flat-shading -I/usr/X11R6/include/ -L/usr/X11R6/lib -lX11 -lglut -LGLU -I/usr/include/eigen3/
	g++ sphere_scene_gouraud-shading.cpp -o sphere_scene_gouraud-shading -I/usr/X11R6/include/ -L/usr/X11R6/lib -lX11 -lglut -LGLU -I/usr/include/eigen3/
	g++ sphere_scene_per-pixel.cpp -o sphere_scene_per-pixel -I/usr/X11R6/include/ -L/usr/X11R6/lib -lX11 -lglut -LGLU -I/usr/include/eigen3/
